### ISSUE TITLE
Doubts about Implementation of Electronic Health Record system 

### ISSUE THREAD

**Issue by anupama12sg** [aditya172926/Electronic_health_records#1]
Hi Aditya!
I have a few questions regarding your project:
1. Can you elaborate on how the system will maintain clear transaction logs for every change in the data and how this improves transparency?
2. What are the potential challenges or drawbacks of implementing a blockchain-based healthcare record system, and how does the paper propose to mitigate them?
3. How does this proposed solution compare to existing electronic healthcare record systems in terms of cost, efficiency, and user-friendliness?

**Comment by aditya172926** [comment]
1. all the references to the data are maintained in a public blockchain. But only available to those who have the access to retrieve those references linking to the patient data.
2. it can be expensive. it is not a good practice to charge the users every time they do an update. Uploading the data directly to blockchain is not a completely practical use-case or a correct one. There is a lot of work remaining in evolving this idea.
3. this system can be costly and not very friendly to users who don't know about tech. Hence we can add functions to abstract a lot of technical things from the users like account abstraction and paymasters.
